## TensorFlow 2 quickstart for beginners

In [3]:
!pip install tensorflow

  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached termcolor-2.4.0-py3-none-any.whl.metadata (6.1 kB)
  Using cached keras-3.4.1-py3-none-any.whl.metadata (5.8 kB)
  Using cached tensorflow_io_gcs_filesystem-0.37.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
  Using cached rich-13.7.1-py3-none-any.whl.metadata (18 kB)
  Using cached namex-0.0.8-py3-none-any.whl.metadata (246 bytes)
  Using cached optree-0.12.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (47 kB)
  Using cached 

In [7]:
import os
os.environ['TF_ENABLE_ONEDNN_OPTS']='0'

In [9]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.17.0


加載並準備 MNIST 數據集。圖像的像素值範圍是從 0 到 255。通過將這些值除以 255.0 將它們縮放到 0 到 1 的範圍，將樣本數據從整數轉換為浮點數：  

因為浮點數有更高的精度，更適合用於神經網絡的計算。  

數據集被存儲在 Google 的雲存儲中，TensorFlow 團隊為了方便用戶提供的數據集下載鏈接。  
mnist.npz 是一個 NumPy 格式的壓縮文件，內含訓練集和測試集的圖像數據及其對應的標籤。

In [12]:
mnist = tf.keras.datasets.mnist
# 加載 MNIST 數據集，會自動檢查本地是否已經存在
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# 將像素值縮放到 0 到 1 的範圍
x_train = x_train / 255.0
x_test = x_test / 255.0

In [16]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [17]:
x_test

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

* Keras 提供了一個簡單且一致的 API，使得構建和訓練神經網絡變得更加容易。相比於直接使用低層 TensorFlow 操作，Keras 的高層 API 可以讓開發者更加專注於模型設計而不是底層實現細節。
* Keras 的模型是模塊化的，可以輕鬆地組合不同的層、激活函數、優化器等，這使得實驗和調試變得更快捷。

* layers 和 models 是 Keras 中的核心模塊，使用這行代碼可以簡化在構建神經網絡模型時的代碼書寫，使代碼更加簡潔和易讀。

* Keras 的 layers 模塊包含了構建神經網絡層的所有基本組件，比如 Dense 層、卷積層、池化層等。models 模塊則包含了構建和編譯模型的工具，比如 Sequential 和 Model 類。

In [14]:
from tensorflow.keras import layers, models

In [15]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

註：若模型中的最後一層要用softmax，則改成：layers.Dense(10, activation='softmax')


In [18]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.23420343,  0.11045586, -0.07002977,  0.25856367, -0.2247243 ,
        -1.020943  ,  0.6223849 ,  0.34172758,  0.35149777,  0.675537  ]],
      dtype=float32)

tf.nn.softmax 函數將 logits 轉換為每個類別的概率。  
softmax 函數的作用是將一個向量轉換為一個概率分佈，使得每個值都在 0 到 1 之間，且所有值的總和為 1。這在分類問題中非常有用，因為它可以將模型的輸出轉換為可解釋的概率。

In [19]:
tf.nn.softmax(predictions).numpy()

array([[0.06620129, 0.09344372, 0.07801287, 0.10836089, 0.0668318 ,
        0.03014324, 0.15591149, 0.11775793, 0.11891409, 0.16442269]],
      dtype=float32)

Define a loss function for training using losses.SparseCategoricalCrossentropy:  

模型輸出是 logits，而不是已經通過 softmax 處理的概率。

SparseCategoricalCrossentropy適用於分類問題。  
設置 from_logits=True 時，損失函數會將輸入視為未經過 softmax 函數處理的 logits，此時損失函數的計算公式為$loss=-log(\frac{e^{z_i}}{\sum_{j}e^{z_j}})$。這種設置確保了計算的數值穩定性，避免了在計算 softmax 和損失時可能出現的數值不穩定問題。  


In [22]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn

用來計算損失函數在給定輸入上的輸出結果。  

In [25]:
# loss_fn 為損失函數，在上方被定義。
# y_train 是訓練數據的標籤。
# y_train[:1] 取的是訓練數據標籤中的第一個樣本。
# predictions 是模型對一些輸入數據的預測結果，通常是 logits。

# 計算 y_train[:1] 和 predictions 之間的損失。
# y_train[:1] 是真實標籤，predictions 是模型的預測輸出（logits）。
loss_fn(y_train[:1], predictions).numpy()

3.5017948

進行模型訓練之前，使用 Keras 的 Model.compile 方法配置和編譯模型是至關重要的。這個過程確保了模型在訓練過程中能夠使用指定的優化器、損失函數以及評估指標。  
* 設定優化器 (Optimizer)  
  優化器是用來更新模型權重的算法。adam 是一種常用的自適應學習率優化算法，具有較好的性能和收斂速度。這個優化器會根據梯度信息自動調整學習率。
* 設定損失函數 (Loss Function)  
  損失函數用於計算模型預測結果與實際標籤之間的誤差。在之前的步驟中，已經定義了一個損失函數 loss_fn。這個損失函數會根據模型的輸出和實際標籤計算損失值，用於指導模型的訓練過程。
* 設定評估指標 (Metrics)  
  評估指標用於在訓練過程中監控模型的性能。accuracy 是一個常見的指標，用於測量模型的預測正確率。
  

In [26]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

## Train and evaluate your model  

model.fit 方法用於訓練模型，它會迭代地更新模型的權重以最小化損失函數。這個方法接受多個參數，其中最基本的包括訓練數據、標籤和訓練的輪數（epochs）。
* x_train  
  這是模型用來學習的輸入數據。
* y_train  
  這是每個樣本的真實標籤。
* epochs  
  訓練的輪數。每輪訓練包括了使用所有訓練數據一次。這裡的 epochs=5 表示模型將會在整個訓練數據上訓練 5 輪。

### model.fit 的運行過程  
1. 初始化訓練：
   * 開始訓練過程，模型的權重會根據初始設置進行初始化。
2. 迭代訓練：
   * 在每一個 epoch 中，模型會通過所有的訓練數據。這過程中，模型會使用優化器計算梯度，並更新權重以最小化損失函數。
   * 每個 epoch 都會計算並記錄訓練過程中的損失和評估指標（如準確率）。
3. 更新權重：
   * 在每個批次（batch）中，模型的權重會被更新。這是基於該批次數據的損失值和梯度計算來完成的。
4. 訓練結束：
   * 當所有的 epochs 完成後，訓練過程結束。模型的最終權重會基於所有 epochs 的累積更新結果來確定。

In [27]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8546 - loss: 0.4943
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9541 - loss: 0.1509
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9662 - loss: 0.1073
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9723 - loss: 0.0877
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9777 - loss: 0.0726


Model.evaluate 方法用於評估模型的性能，這個方法通常用於驗證集或測試集上，以檢查模型在這些新數據上的表現，有助於理解模型在訓練之外的數據上的準確性和效果。  
1. x_test
   * 這是用來評估模型性能的輸入數據。在這個例子中，x_test 是 MNIST 數據集中的測試數據（圖像），形狀為 (num_test_samples, 28, 28)。
2. y_test
   * 這是對應於 x_test 的真實標籤。在這個例子中，y_test 是每張測試圖像所對應的數字標籤，值為 0 到 9 之間的整數。
3. verbose
   * 控制顯示進度的詳細程度。
     * verbose=0：不顯示進度條。
     * verbose=1：顯示進度條。
     * verbose=2：顯示每個 epoch 的進度信息（更詳細）。

In [32]:
model.evaluate(x_test,  y_test, verbose=1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9742 - loss: 0.0870


[0.07492344081401825, 0.9776999950408936]

In [33]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 1ms/step - accuracy: 0.9777 - loss: 0.0749


[0.07492344081401825, 0.9776999950408936]

probability_model 定義了如何將 Softmax 層附加到已經訓練過的模型上，從而將模型的輸出轉換為概率。  

1. tf.keras.Sequential:
   * 這是一種線性堆疊模型的方式。它允許你按順序添加層，每一層的輸出作為下一層的輸入。
2. model:
   * 這是你之前定義並訓練好的模型。它的最後一層是沒有 Softmax 的，因此它輸出的是 logits，即每個類別的原始分數。
3. tf.keras.layers.Softmax():
   * 這是一個 Softmax 層，將模型的 logits 轉換為概率。Softmax 函數會將每個輸出值轉換為一個範圍在 [0, 1] 之間的值，這些值的總和為 1。這樣每個輸出值就可以解釋為該類別的預測概率。

In [36]:
# 定義一個新的模型來附加 softmax
probability_model = tf.keras.Sequential([
  model, # 添加訓練好的模型
  tf.keras.layers.Softmax() # 在最後添加 softmax 層
])
# probability_model 將返回概率

In [37]:
# 對 x_test 中前 5 個樣本進行預測，並返回這些樣本的預測概率。
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.84399590e-07, 3.03455172e-09, 8.98396138e-06, 3.65933054e-04,
        6.33458347e-12, 4.60282251e-07, 1.94427638e-14, 9.99617577e-01,
        6.49230092e-09, 6.73752493e-06],
       [3.33506250e-07, 1.49640284e-04, 9.99723017e-01, 1.26358616e-04,
        2.54291132e-14, 1.64139152e-07, 1.88044353e-07, 5.85454536e-13,
        2.22729057e-07, 4.21029449e-14],
       [3.87061121e-08, 9.99527097e-01, 4.11563269e-05, 3.44077620e-07,
        4.94278211e-05, 6.52550216e-06, 2.21942537e-05, 3.43160704e-04,
        9.33864521e-06, 7.29520536e-07],
       [9.99992728e-01, 1.73897789e-11, 1.68775614e-07, 6.37276321e-09,
        1.80174684e-08, 1.36880061e-07, 6.68090206e-06, 1.16750705e-07,
        1.41076373e-09, 2.32554356e-07],
       [2.27878559e-06, 1.29445521e-08, 1.46292916e-06, 4.37150049e-08,
        9.94175911e-01, 2.78768823e-07, 3.64977791e-06, 1.56802253e-05,
        1.14691568e-06, 5.79956872e-03]], dtype=float32)>